Kinto integration
KintoXYZ/socket-plugs pull request #1
Opened 2024-05-06 15:52 UTC by fedealconada

2024-05-10 13:59 UTC, ylv-io commented on contracts/hooks/KintoHook.sol
> + * @notice TODO
TODO?

2024-05-10 13:59 UTC, ylv-io commented on contracts/hooks/KintoHook.sol
> +     * @param owner_ Owner of this contract.
Other params?

2024-05-10 21:44 UTC, rrecuero commented on contracts/hooks/KintoHook.sol
> +        if (!kintoID.isKYC(params_.msgSender)) revert KYCRequired();
The sender is mostly going to be a wallet here right?

We should check that the sender is a valid wallet and that its first signer is KYC, can we also check that the destination withdrawal address is also part of the funder whitelist?

2024-05-10 21:47 UTC, rrecuero requested changes
Need to change the srcPreHook

2024-05-14 14:19 UTC, ylv-io approved these changes
🚢

2024-05-22 02:42 UTC, merged